* My NixOS Configuration
** Hosts
*** Kronos
~God of harvests and personification of destructive time. The leader of the Titans.~
+ Fujitsu CELSIUS W530
+ Intel Xeon E3-1270 v3 (8) @ 3.900GHz
+ NVIDIA Quadro K2000
+ 16GiB DDR3 RAM
*** Hermes
~God of boundaries, travel, trade, communication, language, writing, cunning and thieves.~
+ Lenovo ThinkPad T480
+ Intel i7-8550U (8) @ 4.000GHz
+ Intel UHD Graphics 620
+ NVIDIA GeForce MX150
+ 16GiB DDR4 RAM
*** Nyx
~The goddess of night.~
+ Lenovo ThinkPad P50
+ Intel i7-6700HQ (8) @ 3.500GHz 
+ Intel HD Graphics 530
+ NVIDIA Quadro M1000M
+ 8GiB DDR4 RAM
*** Apollo
~God of music, arts, knowledge, healing, plague, prophecy, poetry, manly beauty, and archery.~
+ Lenovo ThinkPad T420

** Credits
+ https://github.com/nrdxp/devos
+ https://github.com/gytis-ivaskevicius/flake-utils-plus
+ Inspiration:
  + https://github.com/gytis-ivaskevicius/nixfiles
  + https://github.com/fufexan/dotfiles

** License

The MIT License (MIT)

Copyright (c) 2021 Marvin Strangfeld

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
